# Generated by Django 3.2.5 on 2023-02-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('data', models.FileField(upload_to='pdf')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
